config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index' #, as: 'home'
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  #devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks' }
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  #devise_for :users


  # devise_scope :user do
  #   delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end
  
  resources :home, only: :index
  resources :category, only: [:index, :show]
  resources :authors, only: [:index, :show]

  resources :books, only: [:index, :show] do
    resources :ratings, only: [:new, :create]
  end
  # get "/ratings/new" => "ratings#new" 
  # resources :rating, only: :new
  
  resources :orders, only: [:index, :show, :update, :destroy]

  resources :order_items, except: [:new, :show, :edit]
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :book_authors
  has_many :authors, through: :book_authors

  has_many :category_books
  has_many :categories, through: :category_books

  has_many :ratings, dependent: :destroy

  has_many :order_items
  before_destroy :ensure_not_referenced_by_any_order_item

  validates :title, :price, :qty, presence: true
  validates :price, numericality: { greater_than: 0 }
  validates :qty, numericality: { greater_than_or_equal_to: 1 }

  private

  # ensure that there are no line items referencing this product
  def ensure_not_referenced_by_any_order_item
    if order_items.empty?
      return true
    else
      errors.add(:base, 'Order Items present')
      return false
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :destroy]

  def index
    @books = Book.all.page(params[:page]).per(12)
    @categories = Category.all

  #   @category = Category.find(params[:category]) if params[:category]
  #   if @category
  #     @books = Book.where(category: @category.id)
  #   else
  #     @books = Book.all
  #   end
  # #   @categories = Category.all
  end

  def show
    book = Book.find(params[:id])
    @order_item = OrderItem.new
  end


  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # def book_params
    #   params.require(:book).permit(:title, :description, :price, :qty)
    # end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<div class="col-md-4">
  <%= link_to image_tag('book.jpg'), book_path(book) %>
  <div class="title">
    <%= link_to( book.title, book_path(book)) %>
  </div>
  <div class="price">
    <strong>
      <%= number_to_currency(book.price) %>
    </strong>
  </div>
</div>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :qty %><br>
    <%= f.number_field :qty %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/index.html.erb
<div class="container" style="margin-top: 50px;">
  
  <div class="row">
    <strong>
      <h2>Shop</h2>
    </strong>
    <div class="col-md-9">
      <%= render @books %>
    </div>
    <div class="col-md-3">
      <div class="row">
        <strong>
          SHOP BY CATEGORIES
        </strong>
      </div>
      <% @categories.each do |category| %>
        <div class="row">
          <h4><%= link_to "#{category.title}", category %></h4>
        </div>
      <% end %>
    </div>
  </div>
  <div class="text-center">
    <%= paginate @books %>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-9" style="margin-top: 50px;">
      <% if notice %>
        <p id="notice"><%= notice %></p>
      <% end %>
      <p>
        <%= image_tag(@book.image) %>
      </p>
      <p>
        <h4>
          <%= @book.title %>
        </h4>
      </p>
      <p>
        <%= @book.description %>
      </p>
      <p>
        <strong>Authors:</strong>
        <% @book.authors.each do |author| %>
          <%= link_to author.name, author %>
        <% end %>
        <!--<%= @book.authors.pluck(:name).join(", ") %> /-->
      </p>
      <p>
        <h3>
          <%= number_to_currency(@book.price) %>
        </h4>
      </p>
      
      <p>
        <%= form_for @order_item do |f| %>
          <%= f.number_field :quantity, min: 1, max: 5, value: 1, class: 'input-mini' %>
          <%= f.hidden_field :book_id, value: @book.id %>
          <%= f.submit 'Add to cart', class: 'btn btn-default btn btn-primary' %>
        <% end %>
      </p>
      
      <div class="ratings">
        <p class="pull-right">
          <%= @book.ratings.count %>
          reviews
        </p>
        <p>
          <strong>Rating:</strong>
          <% 5.times do |n| %>
            <% if @book.ratings.average(:value).nil? %>
              Not a rating
              <% break %>
            <% elsif @book.ratings.average(:value).ceil > n %>
              <span class="glyphicon glyphicon-star"></span>
            <% else %>
              <span class="glyphicon glyphicon-star-empty"></span>
            <% end %>
          <% end %>
          <%= number_with_precision(@book.ratings.average(:value), precision: 2) %>
        </p>
      </div>
      <%= link_to 'Add a review', new_book_rating_path(@book), class: 'btn btn-info' %>
      <hr>


      <% @book.ratings.each do |rating| %>
        <div class="row">
          <div class="col-md-12">
            <p>
              <span class="date">
                <%= rating.updated_at.strftime("%B %d, %Y") %>
              </span>
            </p>
            <p>
              <% 5.times do |n| %>
                <% if rating.value > n %>
                  <span class="glyphicon glyphicon-star"></span>
                <% else %>
                  <span class="glyphicon glyphicon-star-empty"></span>
                <% end %>
              <% end %>
              <strong>
                <%= rating.value %>
              </strong>
              <p>
                <%= rating.review %>
              </p>
            </p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <%= link_to 'Back', books_path %>
</div>