config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index' #, as: 'home'
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  #devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks' }
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  #devise_for :users


  # devise_scope :user do
  #   delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end
  
  resources :home, only: :index
  resources :category, only: [:index, :show]
  resources :authors, only: [:index, :show]

  resources :books, only: [:index, :show] do
    resources :ratings, only: [:new, :create]
  end
  # get "/ratings/new" => "ratings#new" 
  # resources :rating, only: :new
  
  resources :orders, only: [:index, :show, :update, :destroy]

  resources :order_items, except: [:new, :show, :edit]
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :book
  belongs_to :order

  validates :price, :quantity, presence: true

  def total_price
    book.price * quantity
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  
  include CurrentOrder
  
  before_action :set_order, only: [:create]
  before_action :set_order_item, only: [:show, :edit, :update, :destroy]


  def index
    @order_items = OrderItem.all
  end

  def show
  end

  def new
    @order_item = OrderItem.new
  end

  def edit
  end


  def create
    @order.add_book(params[:order_item][:book_id], params[:order_item][:quantity].to_i)
    redirect_to :back
  end

  
  # def create

  #   book = Book.find(params[:order_item][:book_id])
  #   # @order_item = @order.order_items.build(book: book, price: book.price, quantity: params[:order_item][:quantity])
  #   @order_item = @order.add_book(book.id)

  #   respond_to do |format|
  #     if @order_item.save
  #       format.html { redirect_to @order_item.order,
  #         notice: 'Order item was successfully created.' }
  #       format.json { render action: 'show',
  #         status: :created, location: @order_item }
  #     else
  #       format.html { render action: 'new' }
  #       format.json { render json: @order_item.errors,
  #         status: :unprocessable_entity }
  #     end
  #   end
  # end

  def update
    @order_item.update(order_item_params)
    render nothing: true
  end

  def destroy
    @order_item.destroy
    respond_to do |format|
      format.html { redirect_to :back, :notice => 'Item has been removed from your cart.' }
      format.json { head :ok }
    end
  end

  private

  def set_order_item
    @order_item = OrderItem.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def order_item_params
    params.require(:order_item).permit(:book_id, :price, :quantity)
  end
end

app/views/order_items/_form.html.erb
<%= form_for(@order_item) do |f| %>
  <% if @order_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @order_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :book %><br>
    <%= f.text_field :book %>
  </div>
  <div class="field">
    <%= f.label :order %><br>
    <%= f.text_field :order %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/order_items/edit.html.erb
<h1>Editing order_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @order_item %> |
<%= link_to 'Back', order_items_path %>

app/views/order_items/index.html.erb
<h1>Listing order_items</h1>

<table>
  <thead>
    <tr>
      <th>Book</th>
      <th>Order</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @order_items.each do |order_item| %>
      <tr>
        <td><%= order_item.book %></td>
        <td><%= order_item.order %></td>
        <td><%= link_to 'Show', order_item %></td>
        <td><%= link_to 'Edit', edit_order_item_path(order_item) %></td>
        <td><%= link_to 'Destroy', order_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order item', new_order_item_path %>

app/views/order_items/new.html.erb
<h1>New order_item</h1>

<%= render 'form' %>

<%= link_to 'Back', order_items_path %>

app/views/order_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Book:</strong>
  <%= @order_item.book %>
</p>

<p>
  <strong>Order:</strong>
  <%= @order_item.order %>
</p>

<%= link_to 'Edit', edit_order_item_path(@order_item) %> |
<%= link_to 'Back', order_items_path %>