config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index' #, as: 'home'
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  #devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks' }
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  #devise_for :users


  # devise_scope :user do
  #   delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end
  
  resources :home, only: :index
  resources :category, only: [:index, :show]
  resources :authors, only: [:index, :show]

  resources :books, only: [:index, :show] do
    resources :ratings, only: [:new, :create]
  end
  # get "/ratings/new" => "ratings#new" 
  # resources :rating, only: :new
  
  resources :orders, only: [:index, :show, :update, :destroy]

  resources :order_items, except: [:new, :show, :edit]
end

app/models/address.rb
class Address < ActiveRecord::Base
  
  #belongs_to :country

  validates :address, :zip, :city, :phone, :country, presence: true
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :book_authors
  has_many :books, through: :book_authors

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :book_authors
  has_many :authors, through: :book_authors

  has_many :category_books
  has_many :categories, through: :category_books

  has_many :ratings, dependent: :destroy

  has_many :order_items
  before_destroy :ensure_not_referenced_by_any_order_item

  validates :title, :price, :qty, presence: true
  validates :price, numericality: { greater_than: 0 }
  validates :qty, numericality: { greater_than_or_equal_to: 1 }

  private

  # ensure that there are no line items referencing this product
  def ensure_not_referenced_by_any_order_item
    if order_items.empty?
      return true
    else
      errors.add(:base, 'Order Items present')
      return false
    end
  end
end

app/models/book_author.rb
class BookAuthor < ActiveRecord::Base
  belongs_to :book
  belongs_to :author
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :category_books
  has_many :books, through: :category_books

  validates :title, presence: true, uniqueness: true
end

app/models/category_book.rb
class CategoryBook < ActiveRecord::Base
  belongs_to :category
  belongs_to :book
end

app/models/country.rb
class Country < ActiveRecord::Base
  
  #has_many :addresses

  belongs_to :address
  validates :name, presence: true, uniqueness: true
end

app/models/credit_card.rb
class CreditCard < ActiveRecord::Base
  belongs_to :user
  has_many :orders

  validates :number, presence: true
  validates :cvv, presence: true
  validates :expiration_month, presence: true
  validates :expiration_year, presence: true
  validates :firstname, presence: true
  validates :lastname, presence: true
end

app/models/order.rb
class Order < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :credit_card
  
  has_many   :order_items, dependent: :destroy
  
  belongs_to :billing_address, class_name: 'Address',  foreign_key: :billing_address_id
  belongs_to :shipping_address, class_name: 'Address', foreign_key: :shipping_address_id
  
  

  # validates :total_price, :completed_date, :state, presence: true
  # validates :total_price, numericality: true
  # validates :state, inclusion: { in: ['In progress', 'Completed', 'Shipped'] }

  

  
  def add_book(book_id, qty)
    if order_item = self.order_items.find_by(book_id: book_id)
      order_item.quantity += qty
      order_item.price += order_item.book.price * qty
    else
      order_item = self.order_items.new(book_id: book_id, quantity: qty)
      order_item.price = order_item.book.price * qty
    end
    order_item.save
  end

  def total_price
    order_items.to_a.sum { |item| item.total_price }
  end


  # def add_book(book_id)

  #   current_item = order_items.find_by(book_id: book_id)
  #   if current_item
  #     current_item.quantity += 1
  #   else
  #     current_item = order_items.build(book_id: book_id)
  #   end
  #   current_item
  # end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :book
  belongs_to :order

  validates :price, :quantity, presence: true

  def total_price
    book.price * quantity
  end
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :book
  belongs_to :user

  validates :value, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 10 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :orders
  has_many :ratings
  has_many :orders, dependent: :destroy
  has_one  :credit_card, dependent: :destroy

  #has_many  :billing_address, class_name: 'Address',  foreign_key: :billing_address_id
  #has_many  :shipping_address, class_name: 'Address', foreign_key: :shipping_address_id

  validates :email, :password, :firstname, :lastname, presence: true
  validates :email, uniqueness: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, 
         :validatable, :omniauthable,
         :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.firstname = auth.info.name.split[0]   # assuming the user model has a name
      user.lastname = auth.info.name.split[1]
      # user.image = auth.info.image # assuming the user model has an image
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :destroy]

  def index
    @books = Book.all.page(params[:page]).per(12)
    @categories = Category.all

  #   @category = Category.find(params[:category]) if params[:category]
  #   if @category
  #     @books = Book.where(category: @category.id)
  #   else
  #     @books = Book.all
  #   end
  # #   @categories = Category.all
  end

  def show
    book = Book.find(params[:id])
    @order_item = OrderItem.new
  end


  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # def book_params
    #   params.require(:book).permit(:title, :description, :price, :qty)
    # end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @books = Book.all.order(id: :desc).page(params[:page]).per(12)
    @categories = Category.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rating_helper.rb
module RatingHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  
  <head>
    <title>Bookstore</title>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
  </head>
  
  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button class="navbar-toggle" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to t('BookStore'), '/', class: "navbar-brand" %>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li>
              <%= link_to 'Authors', authors_path %>
            </li>
            <li>
              <%= link_to 'Books', books_path %>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to(orders_path) do %>
                <span class="glyphicon glyphicon-shopping-cart"></span>
                <%= "Cart: (#{ session[:order].nil? ? "EMPTY" : session[:order].order_item.inject(0){|sum, x| sum + x} })" %>
              <% end %>
            </li>
            <% if signed_in? %>
              <li>
                <%= link_to "Settings (#{current_user.firstname})", edit_user_registration_path %>
              </li>
              <li>
                <%= link_to 'Orders', orders_path %>
              </li>
              <li>
                <%= link_to 'Log out', destroy_user_session_path, :method => :delete %>
              </li>
            <% else %>
              <li>
                <%= link_to 'Sign up', new_user_registration_path %>
              </li>
              <li>
                <%= link_to 'Sign in', user_session_path %>
              </li>
              <li>
                <%= link_to(user_omniauth_authorize_path(:facebook)) do %>
                  <span class="fa fa-facebook-official"></span>
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <% flash.each do |type, content| %>
        <% if content.respond_to?('each') %>
          <% content.each do |item| %>
            <%= render 'layouts/alert', type: type, content: item %>
          <% end %>
        <% else %>
          <%= render 'layouts/alert', type: type, content: content %>
        <% end %>
      <% end %>
    </div>
    <%= yield %>
    <div class="container">
      <hr/>
      <footer class="footer">
        <div class="row">
          <div class="col-lg-12 text-center">
            <p>
              Copyright &copy; 
              <%= Time.now.year %>
            </p>
          </div>
        </div>
      </footer>
    </div>
  </body>
</html>